if [ -f /etc/zprofile ]; then
	source /etc/zprofile
fi

if [ -f ~/.ssh/env ]; then
   source ~/.ssh/env
fi

export LESS=-iFeRX
export TERM=xterm-color

PATH=${PATH}:/Users/jari/git/boots/bin:/opt/homebrew/bin

# OpenJDK
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk@17/include"

# VSCode as default editor
export EDITOR='cursor -w'

# Created by `pipx` on 2025-09-24 13:06:55
export PATH="$PATH:/Users/jari/Library/Python/3.9/bin"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

# Orion Azure
export AZURE_OPENAI_ENDPOINT=https://oai-rhea-ai-dev-we-001.openai.azure.com:8291
