if [ -f /etc/zprofile ]; then
	source /etc/zprofile
fi

if [ -f ~/.ssh/env ]; then
   source ~/.ssh/env
fi

export LESS=-iFeRX
export TERM=xterm-color

PATH=${PATH}:/Users/jari/git/boots/bin:/opt/homebrew/bin

# OpenJDK
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

# VSCode as default editor
export EDITOR='code -w'
