if [ -f /etc/zshrc ]; then
	source /etc/zshrc
fi

# oh-my-zsh
export ZSH="/Users/jari/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
unsetopt share_history

source "$(brew --prefix)/share/antigen/antigen.zsh"
antigen bundle lukechilds/zsh-nvm
antigen apply

alias grep='grep --color=auto'
alias ssh='LANG=en ssh'

# Emacs Client
alias ec='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -c'

# JavaScript
alias yadd='yarn add'
alias yadd-dev='yarn add -D'
alias nadd='npm install -S -E'
alias nadd-dev='npm install -D -E'

alias priva-git='git config user.email "jari+git@iki.fi"; git config sendemail.from "jari+git@iki.fi"'
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"

alias oath='ykman oath code -s $@ | pbcopy'

# Usage:
# awsCliSession <your-aws-profile-name>
# Your AWS profile name should also match the yubikey OATH key name for this to work
awsCliSession () {
  mfa=$(aws iam list-mfa-devices --profile "$1" --query 'MFADevices[0].SerialNumber' --output text)
  credentials=$(aws sts get-session-token --profile "$1" --serial-number "${mfa}" --token-code $(ykman oath accounts code -s "$1"))
  export AWS_PROFILE=$1
  export AWS_ACCESS_KEY_ID=$(echo $credentials | jq -r '.Credentials.AccessKeyId')
  export AWS_SECRET_ACCESS_KEY=$(echo $credentials | jq -r '.Credentials.SecretAccessKey')
  export AWS_SESSION_TOKEN=$(echo $credentials | jq -r '.Credentials.SessionToken')
}

alias awsLogout='unset AWS_PROFILE AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN'

export NVM_DIR="$HOME/.nvm"
source "$(brew --prefix nvm)/nvm.sh"
source "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm"
function gi() { curl -sLw n https://www.toptal.com/developers/gitignore/api/$@ ;}

# Rust
source "$HOME/.cargo/env"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
