if [ -f /etc/zshrc ]; then
	source /etc/zshrc
fi

# oh-my-zsh
export ZSH="/Users/jari/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
unsetopt share_history

source "$(brew --prefix)/share/antigen/antigen.zsh"
antigen bundle lukechilds/zsh-nvm
antigen apply

alias grep='grep --color=auto'
alias ssh='LANG=en ssh'

# Emacs Client
alias ec='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -c'

# JavaScript
alias yadd='yarn add'
alias yadd-dev='yarn add -D'
alias nadd='npm install -S -E'
alias nadd-dev='npm install -D -E'

# edit tmp file
function tempcode() {
  file=$(mktemp -t temp).$1
  pbpaste >$file
  code $file
}
alias tempjson='tempcode json'

alias priva-git='git config user.email "jari+git@iki.fi"; git config sendemail.from "jari+git@iki.fi"'
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"

alias oath='ykman oath code -s $@ | pbcopy'

export NVM_DIR="$HOME/.nvm"
source "$(brew --prefix nvm)/nvm.sh"
source "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm"
function gi() { curl -sLw n https://www.toptal.com/developers/gitignore/api/$@ ;}

# Rust
source "$HOME/.cargo/env"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"

# Python pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# pnpm
export PNPM_HOME="/Users/jari/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
