if [ -f /etc/zshrc ]; then
	source /etc/zshrc
fi

# oh-my-zsh
export ZSH="/Users/jari/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
unsetopt share_history

source "$(brew --prefix)/share/antigen/antigen.zsh"
antigen bundle lukechilds/zsh-nvm
antigen apply

alias grep='grep --color=auto'
alias ssh='LANG=en ssh'

# Emacs Client
alias ec='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -c'

# edit tmp file
function tempcode() {
  file=$(mktemp -t temp).$1
  pbpaste >$file
  code $file
}
alias tempjson='tempcode json'

alias priva-git='git config user.email "jari+git@iki.fi"; git config sendemail.from "jari+git@iki.fi"'
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"

alias oath='ykman oath code -s $@ | pbcopy'

alias depversion="~/git/home/depversion.py"

function gi() { curl -sLw n https://www.toptal.com/developers/gitignore/api/$@ ;}

function astudio() {
  (/Applications/Android\ Studio.app/Contents/MacOS/studio . >/dev/null 2>&1 &)
}

eval "$(mise activate zsh)"
eval "$(mise hook-env -s zsh)"

eval "$(direnv hook zsh)"
export PATH="$HOME/.local/bin:$PATH"

# Created by `pipx` on 2025-09-24 13:06:55
export PATH="$PATH:/Users/jari/Library/Python/3.9/bin"

alias orion_rdp_tunnel="az network bastion tunnel \
--subscription '44592d61-1dd5-4f88-9b9a-de0ac0463e5b' \
--name 'bast-or-prd-we-001' \
--resource-group 'rg-or-bastion-prd-we-001' \
--target-resource-id '/subscriptions/5a950a74-fc51-459d-ae52-61c3b80dc059/resourceGroups/rg-rhea-tools-dev-we-001/providers/Microsoft.Compute/virtualMachines/lazwerheadevt01' \
--port 8293 \
--resource-port 3389"

alias orion_ssh_tunnel="az network bastion tunnel \
--subscription '44592d61-1dd5-4f88-9b9a-de0ac0463e5b' \
--name 'bast-or-prd-we-001' \
--resource-group 'rg-or-bastion-prd-we-001' \
--target-resource-id '/subscriptions/5a950a74-fc51-459d-ae52-61c3b80dc059/resourceGroups/rg-rhea-tools-dev-we-001/providers/Microsoft.Compute/virtualMachines/lazwerheadevt01' \
--port 8290 \
--resource-port 22"

alias orion_ssh_forwards="ssh -N -p 8290 \
-L 8291:aif-rhea-dev-sc-001.openai.azure.com:443 \
-L 8292:strheabotdevwe001.blob.core.windows.net:443 \
-L 8293:strheabotdevwe001.queue.core.windows.net:443 \
-L 8294:strheascraperdevwe001.blob.core.windows.net:443 \
-L 8295:strheascraperdevwe001.queue.core.windows.net:443 \
-L 8296:srch-rhea-dev-we-001.search.windows.net:443 \
lazwerheadevt01"
