#!/bin/sh

# Android SDK location differs by platform
if [ "$(uname)" = "Darwin" ]; then
    SDK_ROOT="$HOME/Library/Android/sdk"
else
    SDK_ROOT="$HOME/Android/Sdk"
fi

emulator="$SDK_ROOT/emulator/emulator"

configs=($($emulator -list-avds))

default=${configs[0]}

$emulator -avd $default -dns-server 8.8.8.8 $@
